[Logging]
; Set to true to enable debug logging
; Generally this should stay false unless you're reporting an issue or if you just want more detailed logging
DebugLogging = false

[SkillRequirements]
; Skill Requirements for each lock level.
iNoviceLockRequirement = 0
iApprenticeLockRequirement = 25
iAdeptLockRequirement = 50
iExpertLockRequirement = 75
iMasterLockRequirement = 100
